#
# (c) Copyright 2015,2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Config Processor defined variables

keystone_auth_url: "{{ NEU_SVR.consumes_KEY_API.vips.private[0].url }}"
neutron_admin_password:
  "{{ NEU_SVR.consumes_KEY_API.vars.keystone_neutron_password | quote }}"
neutron_admin_project_name: "{{ KEY_API.vars.keystone_service_tenant }}"
neutron_admin_user: "{{ NEU_SVR.consumes_KEY_API.vars.keystone_neutron_user }}"
public_region: "{{ NEU.regions | first }}"

# Other
ca_file: "{{ trusted_ca_bundle }}"
EXT_NET_CIDR: "172.31.0.0/16"
svc_net_name: "SVC"

#
# The default external network network configuration only works in cases
# where we are using the L3 agent external_network_bridge approach (i.e.
# there is no default for provider external networks).
#
default_ext_net: "{%- set break = [] -%}
                  [
                  {%- if network_tag_values is defined -%}
                     {%- for service in network_tag_values -%}
                         {%- for netgroup in network_tag_values[service] -%}
                             {%- if 'neutron.l3_agent.external_network_bridge' in network_tag_values[service][netgroup] -%}
                                 {%- if not break -%}
                                     {%- set provider_attrs = [] -%}
                                     {%- if 'neutron.networks.flat' in network_tag_values[service][netgroup] -%}
                                        {%- do provider_attrs.append('\\'network_type\\': \\'flat\\'') -%}
                                        {%- if 'provider-physical-network' in network_tag_values[service][netgroup]['neutron.networks.flat'] -%}
                                            {%- do provider_attrs.append('\\'physical_network\\': \\'' + network_tag_values[service][netgroup]['neutron.networks.flat']['provider-physical-network'] + '\\'') -%}
                                        {%- endif -%}
                                     {%- elif 'neutron.networks.vlan' in network_tag_values[service][netgroup] -%}
                                        {%- do provider_attrs.append('\\'network_type\\': \\'vlan\\'') -%}
                                        {%- if 'provider-physical-network' in network_tag_values[service][netgroup]['neutron.networks.vlan'] -%}
                                            {%- do provider_attrs.append('\\'physical_network\\': \\'' + network_tag_values[service][netgroup]['neutron.networks.vlan']['provider-physical-network'] + '\\'') -%}
                                        {%- endif -%}
                                        {%- if 'provider-segmentation-id' in network_tag_values[service][netgroup]['neutron.networks.vlan'] -%}
                                            {%- do provider_attrs.append('\\'segmentation_id\\': \\'' + network_tag_values[service][netgroup]['neutron.networks.vlan']['provider-segmentation-id'] + '\\'') -%}
                                        {%- endif -%}
                                     {%- endif -%}
                                     {%- if provider_attrs | length > 0 -%}
                                         {'name': 'ext-net', 'cidr': '{{ EXT_NET_CIDR }}', 'provider': [{ {{ provider_attrs | join(', ') }} }] }
                                     {%- else  -%}
                                         {'name': 'ext-net', 'cidr': '{{ EXT_NET_CIDR }}'}
                                     {%- endif -%}
                                     {%- if break.append(1) -%}{%- endif -%}
                                 {%- endif -%}
                             {%- endif -%}
                         {%- endfor -%}
                     {%- endfor -%}
                 {%- endif -%}
                 ]"

openstack_cmd_args: >
  --os-username {{ neutron_admin_user }}
  --os-project-name {{ neutron_admin_project_name }}
  --os-user-domain-name Default
  --os-project-domain-name Default
  --os-auth-url {{ keystone_auth_url }}
  --os-region-name {{ public_region }}
  --os-interface internal
  --os-cacert {{ ca_file }}
  --os-identity-api-version 3

extnet_data: "
  {%- if config_data is defined and config_data.NEU is defined and config_data.NEU.neutron_external_networks is defined -%}
    {{config_data.NEU.neutron_external_networks }}
  {%- else -%}
    {{ default_ext_net }}
  {%- endif -%}"

supported_prov_net_types:
  - flat
  - vlan
