#
# (c) Copyright 2015,2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# This .yml sets all facts related to neutron_conf_dir and neutron_bin_dir
- include: _set_service_directories.yml

- name: neutron-common | configure | pass neutron_decrypt_key to host
  set_fact:
    neutron_decrypt_key: "{{ hostvars['localhost']['neutron_decrypt_key'] }}"

- name: neutron-common | configure | Set max api worker count to neutron_max_workers if dynamic
    CPU based count is greater than {{ neutron_max_workers }}
  set_fact:
    neutron_api_workers: "{{ neutron_max_workers }}"
  when: neutron_api_workers|int > neutron_max_workers|int

- name: neutron-common | configure | Set max rpc worker count to neutron_max_workers if dynamic
    CPU based count is greater than {{ neutron_max_workers }}
  set_fact:
    neutron_rpc_workers: "{{ neutron_max_workers }}"
  when: neutron_rpc_workers|int > neutron_max_workers|int

- name: neutron-common | configure | Set max metadata worker count to neutron_max_workers if dynamic
    CPU based count is greater than {{ neutron_max_workers }}
  set_fact:
    neutron_metadata_workers: "{{ neutron_max_workers }}"
  when: neutron_metadata_workers|int > neutron_max_workers|int

- name: neutron-common | configure | include pci vars
  include_vars: pci.yml
  when: network_device_types is defined

- name: neutron-common | configure | configure neutron-sudoers
  become: yes
  template:
    src: "neutron-sudoers.j2"
    dest: "/etc/sudoers.d/neutron"
    owner: "root"
    group: "root"
    mode: 0440

# Create the group "neutron" and user "neutron"
- include: _create_user_and_group.yml

# Create common neutron directories
- include: _create_neutron_common_dirs.yml

- name: neutron-common | configure | Create dnsmasq config directory
  become: yes
  file:
    path: "{{ neutron_dnsmasq_conf_dir }}"
    owner: "{{ neutron_user }}"
    group: "{{ neutron_group }}"
    mode: 0750
    state: directory

- include: _configure_rootwrap.yml

- include: _write_conf.yml
  src: "../templates/neutron.conf.j2"
  dest: "neutron.conf"

- name: neutron-common | configure | neutron.conf change
  command: /bin/true
  register:  ardana_notify_neutron_restart_required
  when: write_conf_result.changed==true

- name: neutron-common | configure | Debian - Set datapath_type for dpdk
  set_fact:
    neutron_ovs_datapath_type: "netdev"
  when:
    ansible_os_family == 'Debian' and ansible_processor[0] == 'GenuineIntel' and
    ('NOV-KVM' in group.services and {{ ovs_dpdk_enabled }})

- name: neutron-common | configure | Suse - Set datapath_type for dpdk
  set_fact:
    neutron_ovs_datapath_type: "netdev"
  when:
    ansible_os_family == 'Suse' and ansible_processor[0] == 'GenuineIntel' and
    ('NOV-KVM' in group.services and {{ ovs_dpdk_enabled }})

# Render the configuration files specified in the "provides-data" data,
# option "config_files" provided to neutron-server.
- include: _write_conf_list.yml conf_files={{ neutron_server_config_files }}

- name: neutron-common | configure |
    Check whether _write_conf_list changed ml2_conf.ini
  set_fact:
    ml2_conf_write_result: "{{ write_conf_list_result.results[neutron_server_config_files.index({'source': '../templates/ml2_conf.ini.j2', 'dest': 'ml2_conf.ini'})].changed | bool }}"
  when: "'ml2_conf.ini' in neutron_server_config_dests"

- name: neutron-common | configure |
    Notify neutron_ovs_agent of ml2_conf.ini change
  command: /bin/true
  register: ardana_notify_neutron_ovs_agent_restart_required
  when: ml2_conf_write_result|bool == true

- name: neutron-common | configure |
    Notify neutron-server to restart if _write_conf_list.yml changed cfg files
  command: /bin/true
  register: ardana_notify_neutron_server_restart_required
  when: "write_conf_list_result.changed==true"

- include: _configure_ovsvapp_agent.yml
  when: "'NEU-OVSVAPP' in group.services"

- include: _configure_neutron_server.yml

- include: _configure_openvswitch_agent.yml

- include: _configure_sriov_agent.yml

- include: _configure_dhcp_agent.yml

- include: _configure_metadata_agent.yml

  # vpnaas and fwaas configured as l3 agent services
- include: _configure_l3_agent.yml

- include: _configure_lbaas_agent.yml

- include: _configure_l2gw_agent.yml

- include: _configure_infoblox_ipam_agent.yml
  when: "'NEU-IFBLXA' in group.services"
