#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: neutron-ovsvapp-agent | configure | Create ml2 directory
  become: yes
  file:
    path: "{{ neutron_conf_dir }}/plugins/ml2"
    state: directory
    mode: 0755
    owner: "{{ neutron_user }}"
    group: "{{ neutron_group }}"

- name: neutron-ovsvapp-agent | configure | Create ovsvapp-agent directory
  become: yes
  file:
    path: "{{ neutron_log_dir }}/ovsvapp-agent"
    state: directory
    mode: 0755
    owner: "{{ neutron_user }}"
    group: "{{ neutron_group }}"

- name: neutron-ovsvapp-agent | configure | Change permission for ovsvapp agent
  become: yes
  file:
    path: "{{ neutron_bin_dir }}/neutron-ovsvapp-agent"
    state: file
    mode: 0755

- name: neutron-ovsvapp-agent | configure | Copy ovsvapp_agent.ini file
  become: yes
  command:  cp -rp "{{ neutron_conf_dir }}/ovsvapp_agent.ini"
              "{{ neutron_conf_dir }}/plugins/ml2/ovsvapp_agent.ini"

- name: neutron-ovsvapp-agent | configure | Create ovsvapp agent logrotate file
  become: yes
  file:
    path: /etc/logrotate.d/neutron-ovsvapp-agent
    state: touch
    mode: 0655

- name: neutron-ovsvapp-agent | configure | Copy logrotate configuration
  become: yes
  copy:
    src: etc/logrotate.d/neutron-ovsvapp-agent
    dest: /etc/logrotate.d/neutron-ovsvapp-agent
    owner: root
    group: root
    mode: 0644

- include: ../../neutron-common/tasks/create_systemd_service.yml
  neutron_service_cmd: "neutron-ovsvapp-agent"
  neutron_service_cmd_args:
    "--config-file={{ neutron_conf_dir }}/neutron.conf
      --config-file={{ neutron_conf_dir }}/ml2_conf.ini
      --config-file={{ neutron_conf_dir }}/plugins/ml2/ovsvapp_agent.ini
      --log-file={{ neutron_log_dir }}/ovsvapp-agent/ovsvapp_agent.log"

- name: neutron-ovsvapp-agent | configure | set neutron log file ownership
  become: yes
  file:
    path: "{{ neutron_log_dir }}/{{ item }}"
    owner: "{{ neutron_user }}"
    group: "{{ neutron_centralized_log_group }}"
    mode: 0640
    state: touch
  with_items:
    - ovsvapp-agent/ovsvapp_agent.log
    - ovsvapp-agent/ovsvapp_agent-json.log
